-- CreateEnum
CREATE TYPE "public"."TagType" AS ENUM ('POLITICA', 'ESPORTES', 'ENTRETENIMENTO', 'TECNOLOGIA', 'ECONOMIA', 'MUNDO', 'SAUDE', 'CULTURA', 'CIENCIA', 'OPINIAO', 'ENTREVISTAS', 'REPORTAGENS', 'VIDEOS', 'FOTOS', 'PODCASTS', 'EVENTOS', 'LIFESTYLE', 'VIAGENS');

-- AlterTable
ALTER TABLE "public"."Post" ADD COLUMN     "tags" "public"."TagType"[];
